DROP TABLE IF EXISTS Bid;  
CREATE TABLE Bid (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
price VARCHAR(50) NOT NULL,  
quantity INT(8) NOT NULL  
); 

DROP TABLE IF EXISTS Ask;  
CREATE TABLE Ask (  
id INT AUTO_INCREMENT  PRIMARY KEY,  
price VARCHAR(50) NOT NULL,  
quantity INT(8) NOT NULL  
); 